### ISSUE TITLE
Plugin not present in Wordpress Plugins search

### ISSUE THREAD

**Issue by serhumanos** [manuelcanga/DisplayMetadata#3]
The plugin is not present in "add new plugin" wordpress section

**Comment by manuelcanga** [comment]
Gracias, @serhumanos 

No sé el porqué lo han podido quitar del listado. Lo investigaré. 

Gracias, @serhumanos. 
-P.d: Perdón por tardar en responder (estaba de vacaciones).

**Comment by serhumanos** [comment]
Hola! gracias por responder.
revisé la web de wordpress y muestra este mensaje:
This plugin has been closed as of May 30, 2023 and is not available for download. Reason: Security Issue.
saludos!

**Comment by manuelcanga** [comment]
Hola, @serhumanos ,
Aunque con un poco de tardanza. He solicitado la reactivación del plugin. Me imagino que nada más que lo revisen, lo activarán a los pocos dias.
Gracias nuevamente por todo.
Saludos
