### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by reneyap** [manuelcanga/DisplayMetadata#4]
https://wordpress.org/plugins/display-metadata/

This plugin has been closed as of May 30, 2023 and is not available for download. Reason: Security Issue.

**Comment by manuelcanga** [comment]
Hi, @reneyap,
This was fixed in [v1.0.0](https://github.com/manuelcanga/DisplayMetadata/releases/tag/v1.0.0). Update your plugin, please.
